"use client";
import Image from "next/image";
import { ArrowLeft, Plus, Trash2, UsersRound } from "lucide-react";
import type { ClubData, Member } from "@/lib/types";
import { Empty } from "@/components/ui-kit";
import { Avatar } from "@/components/features/shared";

export function AnggotaView({data,onBack,onAdd,onEdit,onDelete}:{data:ClubData;onBack:()=>void;onAdd:()=>void;onEdit:(member:Member)=>void;onDelete:(id:string)=>void}) {const members=data.members.filter(member=>member.active);return <div className="min-h-[calc(100dvh-88px)] bg-white"><header className="flex h-[89px] items-end gap-4 border-b border-[#e7e7e7] px-4 pb-4"><button onClick={onBack} aria-label="Kembali" className="grid size-10 shrink-0 place-items-center rounded-full border border-[#e7e7e7] bg-white shadow"><ArrowLeft size={24}/></button><h1 className="min-w-0 flex-1 pb-2 text-xl font-bold">Anggota</h1><button onClick={onAdd} className="flex h-10 shrink-0 items-center gap-1 rounded-full border border-[#dedede] px-3 text-sm text-[#5f5f5f]"><Plus size={18}/> Tambah anggota</button></header><div>{members.length?members.map((member,index)=><div key={member.id} className={`flex h-[68px] items-center gap-2 px-4 ${index%2?"bg-[#f9f9f9]":"bg-white"}`}><button onClick={()=>onEdit(member)} className="flex min-w-0 flex-1 items-center gap-2 text-left"><Avatar name={member.name} small/><b className="truncate text-base">{member.name}</b></button><button onClick={()=>onDelete(member.id)} aria-label={`Hapus ${member.name}`} className="grid size-10 place-items-center text-[#ee2737]"><Trash2 size={24}/></button></div>):<Empty icon={<UsersRound/>} title="Belum ada anggota aktif" text="Tambahkan anggota untuk memulai."/>}</div></div>}

export function MemberFormSheet({open,form,setForm,error,onClose,onSave}:{open:boolean;form:Member;setForm:(member:Member)=>void;error:string;onClose:()=>void;onSave:()=>void}) {if(!open)return null;return <div className="fixed inset-y-0 left-1/2 z-[90] flex w-full max-w-[393px] -translate-x-1/2 items-end bg-black/50"><button onClick={onClose} aria-label="Tutup" className="absolute bottom-[358px] right-7 grid size-10 place-items-center rounded-full bg-white shadow"><span className="text-3xl font-light">×</span></button><section className="relative h-[344px] w-full overflow-hidden rounded-t-[24px] bg-white pt-[143px]"><div className="absolute inset-x-0 top-0 h-[72px] bg-[#f2f4ff]"/><div className="absolute left-1/2 top-8 -translate-x-1/2"><div className="grid size-[79px] place-items-center rounded-full bg-[#5a5ed6]"><Image src="/user-round-plus.svg" alt="" width={40} height={40}/></div></div><div className="px-4"><div className="relative"><Image src="/user.svg" alt="" width={24} height={24} className="absolute left-4 top-1/2 -translate-y-1/2"/><input autoFocus value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Nama anggota" className="h-14 w-full rounded-2xl bg-[#f2f2f2] pl-12 pr-4 text-lg outline-none focus:ring-2 focus:ring-[#cfd6ff]"/></div>{error&&<p className="text-sm text-red-600">{error}</p>}</div><footer className="absolute inset-x-0 bottom-0 border-t border-[#e7e7e7] bg-white/90 px-4 pb-8 pt-4"><button onClick={onSave} className="h-12 w-full rounded-full bg-gradient-to-b from-[#7d87ff] to-[#3929b5] font-bold text-white">Simpan</button></footer></section></div>}

export function DeleteMemberSheet({open,member,onClose,onDelete}:{open:boolean;member:Member;onClose:()=>void;onDelete:()=>void}) {if(!open)return null;return <div className="fixed inset-y-0 left-1/2 z-[100] flex w-full max-w-[393px] -translate-x-1/2 items-end bg-black/50"><button onClick={onClose} aria-label="Tutup" className="absolute bottom-[369px] right-6 grid size-10 place-items-center rounded-full bg-white shadow"><span className="text-3xl font-light">×</span></button><section className="relative h-[355px] w-full overflow-hidden rounded-t-[24px] bg-white pt-[108px]"><div className="absolute inset-x-0 top-0 h-[72px] bg-[#ffe8e6]"/><div className="absolute left-1/2 top-9 grid size-[79px] -translate-x-1/2 place-items-center rounded-full bg-[#ee2737] text-white"><Trash2 size={40}/></div><div className="mx-auto w-[320px] text-center"><h2 className="text-2xl font-bold">Hapus anggota?</h2><p className="mx-auto mt-2 max-w-[295px] text-sm font-semibold leading-6">{member.name} akan dihapus dari daftar aktif. Riwayat pembayaran tetap tersimpan.</p></div><footer className="absolute inset-x-0 bottom-0 border-t border-[#e7e7e7] px-4 pb-8 pt-4"><div className="grid grid-cols-2 gap-2"><button onClick={onClose} className="h-12 rounded-full bg-gradient-to-b from-[#eeeeee] to-[#aaaaaa] font-bold">Batal</button><button onClick={onDelete} className="h-12 rounded-full bg-gradient-to-b from-[#ff6565] to-[#b30024] font-bold text-white">Hapus</button></div></footer></section></div>}
